//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAjaxDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FilesDetails
    {
        public int FileID { get; set; }
        public Nullable<int> SynopsisID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual tbl_SynopsisDetails tbl_SynopsisDetails { get; set; }
    }
}
