//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAjaxDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OTP
    {
        public int OTPID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string OTP { get; set; }
    
        public virtual tbl_Registration tbl_Registration { get; set; }
    }
}
